name: Performance CI

on:
  repository_dispatch:
    types: run-tests
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  API-Performance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Performance Test
        run: mvn clean gatling:test
      - uses: actions/upload-artifact@v1
        with:
          name: report
          path: target
      - name: Print Run id
        run: echo $GITHUB_RUN_ID